name: Build test
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      IMAGE_NAME: ib-gateway-docker
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .
    - name: Push to ECR
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-west-1
        image: $IMAGE_NAME
